alleyinteractive/simplechart

app/components/DataInput/DataInput.css, app/components/DataInput/index.js
advance to next step with `NextButton`
=> parse data input on blur or loading sample data

app/components/Chart/Chart.css, app/components/Chart/ChartTypes/NVD3BaseChart/index.js, app/components/Chart/index.js, app/components/ChartBuilder/ChartBuilder.css, app/components/ChartBuilder/index.js, app/components/Widget.js, app/constants/index.js, app/middleware/chartOptionsMiddleware.js, app/reducers/widget/dataReducer.js, app/widget.js
Allows you to place and style the chart title, caption, and credit by rendering HTML markup like:
```
<div class="simplechart-widget">
<div class="simplechart-title"></div>
<div class="simplechart-chart"></div>
<div class="simplechart-caption"></div>
<div class="simplechart-credit"></div>
</div>
```
=> Custom template for widget

app/components/Chart/ChartTypes/DiscreteBarChart/DiscreteBarChartOptions.js, app/components/Chart/ChartTypes/LineChart/LineChartOptions.js, app/components/Chart/ChartTypes/NVD3BaseChart/BaseChartOptions.js, app/components/Chart/ChartTypes/NVD3BaseChart/index.js, app/components/Chart/ChartTypes/StackedAreaChart/StackedAreaChartOptions.js, app/components/ChartBuilder/index.js
For x axis: axis label, rotation of tick labels
For y axis: axis label, domain (range) of y axis
=> Axis options

README.md, app/actions/index.js, app/components/Chart/ChartTypes/NVD3BaseChart/index.js, app/components/Widget.js, app/constants/index.js, app/reducers/widget/dataReducer.js, app/widget.js, mock-api/sampleData1.json, mock-api/sampleData2.json, widget.html
And allow updates by triggering an action on the widget element
=> Bootstrap widgets with local JS data

README.md, app/components/ChartTypeSelector/index.js, app/components/Widget.js, app/middleware/applyColorsMiddleware.js, app/middleware/chartOptionsInitMiddleware.js, app/widget.js, widget.html
Fixes default palette editability; allows setting custom preload message with DOM attribute
=> Palette fix and placeholder

package.json
See https://github.com/alleyinteractive/simplechart/pull/76#discussion_r89199652
=> add test-watch for jest watch use

README.md
Add link to demo site from readme.
=> Add link to demo site

README.md, package.json, webpack.config.js
https://alleyinteractive.atlassian.net/browse/SC-72
End goal is to have the following commands build the app a production environment.
```
npm install
npm start
```
Also, refactored DEVELOPMENT to use node standard NODE_ENV.
=> Prepare Command For Heroku

.babelrc, README.md, webpack.config.js
https://alleyinteractive.atlassian.net/browse/SC-58
- Correctly compile React within webpack for production environments.
- Fix linting errors within webpack config.
=> Prepare React Correctly For Production

app/components/Chart/ChartTypes/NVD3Adapter/index.js, app/constants/chartTypeConfigs/stackedAreaChart.js, app/constants/chartTypes.js, app/middleware/utils/applyYDomain.js, app/reducers/genericReducers.js, package.json
https://alleyinteractive.atlassian.net/browse/SC-73
=> Add Stacked Area Chart

app/components/DataInput/index.js, app/components/Layout/AppComponent/index.js, app/middleware/receiveRawData.js, app/utils/misc.js, app/utils/rawDataHelpers.js
https://alleyinteractive.atlassian.net/browse/SC-68
=> SC-68 Inform user if they try to input multi-series data without a numeric x-axis

dev-webpack.config.js
Fixes an error related to hot module reloading in development environment.
=> Webpack Fix

.eslintrc, app/actions/index.js, app/actions/requestGoogleSheet.js, app/components/DataInput/DataInput.css, app/components/DataInput/DateFormatter/index.js, app/components/DataInput/index.js, app/constants/errorCodesMap.js, app/constants/index.js, app/pages/help/googleSheets.md, app/reducers/bootstrapReducer.js, app/reducers/rootReducer.js, app/utils/bootstrapStore.js, tests/actions/requestGoogleSheet.integration.test.js
https://alleyinteractive.atlassian.net/browse/SC-13
One way to test this is to inject a Google API key with a postMessage. In developer tools run something like this:
```
window.parent.postMessage({messageType: 'bootstrap.new', data: {
'rawData': '',
'chartData': [],
'chartMetadata': {},
'chartOptions': {},
'chartType': '',
'googleApiKey': 'AIzaSyAF1O7lIB1iwW1QaefyS-QUZw1tTWFr2Hc'
}}, '*');
```
=> SC-13 Google Sheets Integration

app/components/DataInput/DataInput.css, app/components/DataInput/index.js
https://alleyinteractive.atlassian.net/browse/SC-91
=> Fix Integration Issue From SC-91

.gitignore, app/constants/dataTransformers.js, package.json, pantheon-deploy.js, wercker.yml
Uses [Wercker](https://wercker.com) to compile the Webpack build and deploy to the Pantheon dev site when there are new commits on the `develop` branch
=> SC-89 wercker deploy

app/reducers/rootReducer.js, app/utils/parseDate.js
https://alleyinteractive.atlassian.net/browse/SC-101
=> SC-101 Fix Date Validation

app/components/ChartSettings/modules/YAxis.js
https://alleyinteractive.atlassian.net/browse/SC-106
=> Fix Changing Y Domain Minimum Value Breaking Chart

app/components/Chart/ChartTypes/NVD3Adapter/index.js
https://alleyinteractive.atlassian.net/browse/SC-103
=> Fix missing custom options in widget app

app/components/Chart/index.js, app/components/Widget.js
https://alleyinteractive.atlassian.net/browse/SC-124
=> Fix Error On Widget Render

app/components/Chart/index.js, app/components/ChartSettings/modules/XAxis.js, app/components/ChartSettings/modules/YAxis.js, app/constants/chartTypes.js, app/reducers/chartOptionsReducer.js, app/reducers/utils/applyYDomain.js
Allow specifying NVD3 margins and axis width (for y-axis) to make sure that axis ticks and labels don't get cut off
=> SC-129 height/width of axes

app/constants/chartTypes.js, tests/reducers/chartOptions.unit.test.js, tests/reducers/utils/applyTickFormatters.unit.test.js
https://alleyinteractive.atlassian.net/browse/SC-132
Also, make the tests pass.
=> Fix Theme Colors Not Being Applied

app/actions/index.js, package.json, polyfills.js, prod-webpack.config.js
=> Consolidate Polyfills and add one for Object.assign

app/components/Chart/Chart.css, app/components/Chart/index.js, index.html, package-lock.json, widget.html
- Make some modifications to tooltips to modify mobile behavior.
=> BR-2153 rollover tweaks

app/components/Chart/Chart.css, app/components/ChartAnnotations/ChartAnnotations.css, app/components/ChartAnnotations/index.js, app/components/ChartSettings/modules/Annotations.js, app/reducers/chartAnnotationsReducer.js, index.html, widget.html
- Add ability to hide connectors to annotations
- Fix a misbehaving style for close-out buttons on tooltips
=> BR-2112 add ability to hide annotation connector

app/utils/dataFormats/nvd3ScatterMultiSeries.js, index.html, package-lock.json, widget.html
Details: https://alleyinteractive.atlassian.net/browse/BR-2107
=> BR 2107 - Allow zero values for scatter plots

index.html, package-lock.json, package.json, polyfills.js, widget.html
Closes: https://alleyinteractive.atlassian.net/browse/BR-2769
- Adds working polyfill for IE11.
=> BR-2769: d3 ie11 fix
